### ISSUE TITLE
[Scenario] Better Timber

### ISSUE THREAD

**Issue by BelKed** [Mezy/UhcCore#37]
Hey Mezy,

I have a suggestion for a **scenario**. In this scenario will like in _Timber_ scenario breaking a log of a tree will cause the whole tree to fall down, but it should be combined with _Fast Leaves Decay_ in which would leaves decay immediately and leaves would drop just apples (not saplings and sticks). Also every log of tree should drop 4 Oak Planks instead Log. I think it is a good feature to speed up the game, so players didn't have to craft planks...

Thanks,
BelKed

**Comment by steamsyyy** [comment]
I think the plank part should be a separate scenario in it's own.

Would look something like

- BETTERTIMBER
- AUTOPLANKS

**Comment by BelKed** [comment]
I think, that would be better have settings for that scenario in _scenarios.yml_. And then you could set there, what would Log from tree drop `log-drop: '{"type":"OAK_PLANK","amount":4}'` or you can disable this feature by writing `custom-drop: false`. Whole setting will be:
```yaml
bettertimber:
    custom-drop: false
    log-drop: '{"type":"OAK_PLANK","amount":4}'
    # Time in seconds to decay leaves. (Set -1 to do not affect default
    # decay time in vanilla minecraft, 0 for immediately decay)
    leaves-decay-time: -1
    leaves-drop: '{"type":"APPLE","amount":1, "chance":"2%"}'
```

Or just there could be implemented those features in default timber scenario – replace `bettertimber` with `timber` in config written higher.
