### ISSUE TITLE
Add multiple drops with percentage support to config.yml

### ISSUE THREAD

**Issue by BelKed** [Mezy/UhcCore#38]
Hey Mezy,

I have a suggestion for a **change**. I think you could add **multiple drops with percentage** support to _config.yml_. So syntax could be like:
```yaml
REDSTONE_ORE:
  loot:
    - '{"type":"NETHER_WART","minimum":1,"maximum":3,"chance":"30%"}'
    - '{"type":"BREWING_STAND","chance":"20%"}'
    - '{"type":"REDSTONE","minimum":1,"maximum":3,"chance":"20%"}'
    - '{"type":"SUGAR","chance":"10%"}'
    - '{"type":"MAGMA_CREAM","chance":"10%"}'
    - '{"type":"BLAZE_POWDER","chance":"10%"}'
  add-xp: 3
```
It would help me and (I think) others a lot.

Thanks,
BelKed
